eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  zipkin:
    base-url: http://eureka-zipkin
  application:
    name: eureka-consumer-1
  sleuth:
    sampler:
      percentage: 1.0