eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
spring:
  zipkin:
    base-url: http://eureka-zipkin
  application:
    name: eureka-consumer
  sleuth:
    sampler:
      percentage: 0.9 